Genera una tabla cargando del excel los datos iniciales de las imágenes, y añadiendo las medidas realizadas por nosotros

In [2]:
import pandas as pd
import numpy as np
import glob
import re
import re
import os

In [3]:
tablepath='datos/medidas.xlsx'
# Echar vistazo a esto https://en.wikipedia.org/wiki/Student%27s_t-distribution#Table_of_selected_values

In [4]:
lambdadisco= {'Halfa-7 nm':656.281,
              'Halfa-35 nm':656.281,
              'Hbeta-8.5nm':486.135}
dlambdadisco={'Halfa-7 nm':7,
              'Halfa-35 nm':35,
              'Hbeta-8.5nm':8.5}
alphap_mas  ={'Sirio':6.04,
              'Rigel':2.77,
              'Betelgeuse':54.04,
              'GammaLeo':7.70}
filtername= {'Halfa-7 nm':'H-alpha (7 nm)',
              'Halfa-35 nm':'H-alpha (35 nm)',
              'Hbeta-8.5nm':'H-beta (8.5 nm)'}
starname={'Sirio':'Sirius',
          'Rigel':'Rigel',
          'Betelgeuse':'Betelgeuse',
          'GammaLeo':'GammaLeo'}

alphap={k:ap*(np.pi/180/1000/3600) for k, ap in alphap_mas.items()} #rad

In [5]:
dts={}#{'D (mm)':np.int16,'L (mm)':np.int16,'L1 (mm)':np.int16,'L2 (mm)':np.int16}
cols=['D (mm)','L (mm)','L1 (mm)','L2 (mm)']
df=pd.read_excel(tablepath,engine="openpyxl",index_col=0,converters=dts                 
                )
df

,Objeto,Filtro,Disco,D (mm),L (mm),L1 (mm),L2 (mm),Notas
Imagen,,,,,,,,
1,Arturo,Halfa-7 nm,D,30,310.0,NaN,NaN,a Borde no encaja
2,Arturo,Halfa-7 nm,D,30,230.0,NaN,NaN,a
3,Arturo,Halfa-7 nm,D,30,150.0,NaN,NaN,a
4,Arturo,Halfa-7 nm,D,30,270.0,NaN,NaN,b
5,Arturo,Halfa-7 nm,D,30,190.0,NaN,NaN,b
6,Arturo,Halfa-7 nm,D,30,60.0,NaN,NaN,fuera de eje
7,Arturo,Halfa-7 nm,D,30,40.0,NaN,NaN,contiguos b
8,Arturo,Halfa-7 nm,D,30,190.0,NaN,NaN,no simetrico
9,Arturo,Halfa-7 nm,D,30,NaN,NaN,NaN,4X

In [6]:
df.dtypes

Objeto      object
Filtro      object
Disco       object
D (mm)       int64
L (mm)     float64
L1 (mm)    float64
L2 (mm)    float64
Notas       object
dtype: object

In [7]:
for c in cols:
    df[c]=pd.to_numeric(df[c],errors='coerce')
df['Filtro']=df['Filtro'].str.strip()
df['Objeto']=df['Objeto'].str.strip()
df['Disco']=df['Disco'].str.strip()

In [8]:
df.dtypes

Objeto      object
Filtro      object
Disco       object
D (mm)       int64
L (mm)     float64
L1 (mm)    float64
L2 (mm)    float64
Notas       object
dtype: object

In [11]:
names=[]
ims=[]
for name in glob.glob('datos/videos/*/*.avi'):
    names.append(name)
    ims.append(int(re.search('\d+', name.split('\\')[-1])[0]))

paths=pd.DataFrame({'PATH':names,'Imagen':ims},index=ims)
paths

                                                PATH  Imagen
1  datos/videos\Arturo\1-2022-07-02-004043-M104-B...       1
2  datos/videos\Arturo\2-2022-07-02-004341-M104-B...       2
3  datos/videos\Arturo\3-2022-07-02-004744-M104-B...       3
4  datos/videos\Arturo\4-2022-07-02-005921-M104-B...       4
5  datos/videos\Arturo\5-2022-07-02-010411-M104-B...       5
6  datos/videos\Arturo\6-2022-07-02-010800-M104-B...       6
7  datos/videos\Arturo\7-2022-07-02-011025-M104-B...       7
8  datos/videos\Arturo\8-2022-07-02-011616-M104-B...       8
9  datos/videos\Arturo\9-2022-07-02-011947-M104-B...       9

In [12]:
df2=df.join(paths)
df2

,Objeto,Filtro,Disco,D (mm),L (mm),L1 (mm),L2 (mm),Notas,PATH,Imagen
Imagen,,,,,,,,,,
1,Arturo,Halfa-7 nm,D,30,310.0,NaN,NaN,a Borde no encaja,datos/videos\Arturo\1-2022-07-02-004043-M104-B...,1
2,Arturo,Halfa-7 nm,D,30,230.0,NaN,NaN,a,datos/videos\Arturo\2-2022-07-02-004341-M104-B...,2
3,Arturo,Halfa-7 nm,D,30,150.0,NaN,NaN,a,datos/videos\Arturo\3-2022-07-02-004744-M104-B...,3
4,Arturo,Halfa-7 nm,D,30,270.0,NaN,NaN,b,datos/videos\Arturo\4-2022-07-02-005921-M104-B...,4
5,Arturo,Halfa-7 nm,D,30,190.0,NaN,NaN,b,datos/videos\Arturo\5-2022-07-02-010411-M104-B...,5
6,Arturo,Halfa-7 nm,D,30,60.0,NaN,NaN,fuera de eje,datos/videos\Arturo\6-2022-07-02-010800-M104-B...,6
7,Arturo,Halfa-7 nm,D,30,40.0,NaN,NaN,contiguos b,datos/videos\Arturo\7-2022-07-02-011025-M104-B...,7
8,Arturo,Halfa-7 nm,D,30,190.0,NaN,NaN,no simetrico,datos/videos\Arturo\8-2022-07-02-011616-M104-B...,8
9,Arturo,Halfa-7 nm,D,30,NaN,NaN,NaN,4X,datos/videos\Arturo\9-2022-07-02-011947-M104-B...,9

In [14]:
df2['$\lambda$']=df2['Filtro'].map(lambdadisco)
df2['$d\lambda$']=df2['Filtro'].map(dlambdadisco)
df2['alphap']=df2['Objeto'].map(alphap)
df2['alphap_mas']=df2['alphap'].apply(lambda x: x/ (np.pi/180/1000/3600))
df2['filtername']=df2['Filtro'].map(filtername)
df2['starname']=df2['Objeto'].map(starname)

In [15]:
# df2['V_exp']=df2['Objeto'].map(starname)

# s='1Sirio0005 Bx3 Halfa 7 nm Inter1_I_D22mm-L220mm_2.4s Gmax 17-03-10 20-48-51.tif'
# re.findall("\d{2}-\d{2}-\d{2}", s.split('\\')[-1])[0]

In [16]:
df2['DATE']=df2['PATH'].apply(lambda x: re.findall("\d{2}-\d{2}-\d{2}", x.split('\\')[-1])[0])
df2['DAY']=df2['DATE'].apply(lambda x:int(x.split('-')[-1]))

In [18]:
df2.head()

,Objeto,Filtro,Disco,D (mm),L (mm),L1 (mm),L2 (mm),Notas,PATH,Imagen,$\lambda$,$d\lambda$,alphap,alphap_mas,filtername,starname,DATE,DAY
Imagen,,,,,,,,,,,,,,,,,,
1,Arturo,Halfa-7 nm,D,30,310.0,NaN,NaN,a Borde no encaja,datos/videos\Arturo\1-2022-07-02-004043-M104-B...,1,656.281,7.0,NaN,NaN,H-alpha (7 nm),NaN,22-07-02,2
2,Arturo,Halfa-7 nm,D,30,230.0,NaN,NaN,a,datos/videos\Arturo\2-2022-07-02-004341-M104-B...,2,656.281,7.0,NaN,NaN,H-alpha (7 nm),NaN,22-07-02,2
3,Arturo,Halfa-7 nm,D,30,150.0,NaN,NaN,a,datos/videos\Arturo\3-2022-07-02-004744-M104-B...,3,656.281,7.0,NaN,NaN,H-alpha (7 nm),NaN,22-07-02,2
4,Arturo,Halfa-7 nm,D,30,270.0,NaN,NaN,b,datos/videos\Arturo\4-2022-07-02-005921-M104-B...,4,656.281,7.0,NaN,NaN,H-alpha (7 nm),NaN,22-07-02,2
5,Arturo,Halfa-7 nm,D,30,190.0,NaN,NaN,b,datos/videos\Arturo\5-2022-07-02-010411-M104-B...,5,656.281,7.0,NaN,NaN,H-alpha (7 nm),NaN,22-07-02,2

In [17]:
# df2['HOUR']=df2['PATH'].apply(lambda x: re.findall("\d{2}-\d{2}-\d{2}", x.split('\\')[-1])[1].replace('-',':'))
df2['HOUR']=df2['PATH'].apply(lambda x: re.findall("\d{2}-\d{2}-\d{2}", x.split('\\')[-1])[1].replace('-',':'))

IndexError: list index out of range

Cargamos la tabla con las medidas originales que realizamos en el aula con imagej

In [102]:
dfV=pd.read_csv("datos/v_individualesyajuster0inicial.csv",sep=';',index_col='indice')[['V_media','S']].rename(columns={'V_media':"V_media_antigua",'S':"S_antigua"})
#dfV=pd.read_csv("datos/medidas_iniciales.csv",sep=';',index_col=1).rename(columns={'MEDIA V':"V_promedio_antigua"})

#tenemos que añadir esto para que funcione el script hasta que metamos los datos nuevos
# dfV['V_media']=dfV['V_media_antigua']
# dfV['S']=dfV['S_antigua']

#Calculamos desviacion tipica
dfV['S_tip_antigua']=dfV['S_antigua']*1/(3**0.5)

In [103]:
dfV

        V_media_antigua  S_antigua  S_tip_antigua
indice
8              0.641222   0.008581       0.004954
9              0.483885   0.015082       0.008708
10             0.322587   0.003800       0.002194
11             0.211979   0.018689       0.010790
4              0.096563   0.003182       0.001837
6              0.439454   0.007861       0.004539
7              0.144100   0.008017       0.004628
13             0.308249   0.003382       0.001953
1              0.094463   0.017632       0.010180
2              0.033639   0.014732       0.008506
3              0.277885   0.002123       0.001226
12             0.342583   0.000277       0.000160
14             0.015108   0.001886       0.001089
15             0.268869   0.013899       0.008025
16             0.139991   0.021037       0.012146
17             0.205609   0.051177       0.029547
18             0.060419   0.002892       0.001669
19             0.372131   0.017874       0.010320
20             0.072809   0.004383       0.002530
21             0.138379   0.003587       0.002071
22             0.226591   0.002237       0.001291
23             0.139635   0.002157       0.001246

In [104]:
df3=df2.join(dfV)

Añadimos los nuevos

In [105]:
numerar=lambda x: int(x) if x!='' else None
dfV=pd.read_csv("datos/repetimos_medidas.csv",sep=';',index_col='Index',converters={"Index":numerar},dtype={"Index":int,"V_media":float,'S':float},na_values=['',"#¡DIV/0!"])[['V_media','S']]
dfV.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3 entries, 8 to 11
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   V_media  3 non-null      float64
 1   S        3 non-null      float64
dtypes: float64(2)
memory usage: 72.0 bytes

c:\Users\ivian\.conda\envs\jupy\lib\site-packages\pandas\util\_decorators.py:311: ParserWarning: Both a converter and dtype were specified for column Index - only the converter will be used.
  return func(*args, **kwargs)

In [106]:
dfV.head(10)

        V_media         S
Index
8      0.632407  0.014108
10     0.294962  0.025108
11     0.219090  0.008554

In [107]:
#Si volvemos a usar esas medidas hay que calcular la desviación tipica aqui tambien
#(de momento para no utilizar los valores repetidos la borramos, habria que comentar)

dfV['V_media']=np.nan
dfV['S']=np.nan
dfV['S_tip']=np.nan

dfV.head(4)

       V_media   S  S_tip
Index
8          NaN NaN    NaN
10         NaN NaN    NaN
11         NaN NaN    NaN

In [108]:


df3=df3.join(dfV)

Copiamos los valores antiguos si no se repitio la medida

In [109]:
df3["V_media"]=df3.apply(lambda row:row["V_media_antigua"] if pd.isna(row["V_media"]) else row["V_media"],axis=1)
df3["S"]=df3.apply(lambda row:row["S_antigua"] if pd.isna(row["S"]) else row["S"],axis=1)
df3["S_tip"]=df3.apply(lambda row:row["S_tip_antigua"] if pd.isna(row["S_tip"]) else row["S_tip"],axis=1)

df3

,Objeto,Filtro,Disco,D (mm),L (mm),L1 (mm),L2 (mm),Notas,PATH,Imagen,...,starname,DATE,DAY,HOUR,V_media_antigua,S_antigua,S_tip_antigua,V_media,S,S_tip
Imagen,,,,,,,,,,,,,,,,,,,,,
1,Sirio,Halfa-7 nm,I,22.0,220.0,NaN,NaN,NaN,datos/imagenes\Sirio\1Sirio0005 Bx3 Halfa 7 nm...,1,...,Sirius,17-03-10,10,20:48:51,0.094463,0.017632,0.010180,0.094463,0.017632,0.010180
2,Sirio,Halfa-7 nm,H,22.0,158.0,NaN,NaN,NaN,datos/imagenes\Sirio\2Sirio0007 Bx3 Halfa 7 nm...,2,...,Sirius,17-03-10,10,20:54:18,0.033639,0.014732,0.008506,0.033639,0.014732,0.008506
3,Sirio,Halfa-7 nm,G,61.0,178.0,NaN,NaN,NaN,datos/imagenes\Sirio\3Sirio0011 Bx3 Halfa 7 nm...,3,...,Sirius,17-03-10,10,21:05:53,0.277885,0.002123,0.001226,0.277885,0.002123,0.001226
4,Rigel,Halfa-7 nm,E,51.0,222.0,NaN,NaN,NaN,datos/imagenes\Rigel\4Rigel0002 Bx3 Halfa7nm I...,4,...,Rigel,17-03-15,15,20:38:22,0.096563,0.003182,0.001837,0.096563,0.003182,0.001837
5,Rigel,Halfa-7 nm,NaN,NaN,NaN,NaN,NaN,Doble,datos/imagenes\Rigel\5Rigel0003 sB Halfa7nm Im...,5,...,Rigel,17-03-15,15,20:43:57,NaN,NaN,NaN,NaN,NaN,NaN
6,Rigel,Halfa-35 nm,F,51.0,147.0,NaN,NaN,NaN,datos/imagenes\Rigel\6Rigel0008 Bx3 Halfa35nm ...,6,...,Rigel,17-03-15,15,21:14:55,0.439454,0.007861,0.004539,0.439454,0.007861,0.004539
7,Rigel,Halfa-35 nm,E,51.0,222.0,NaN,NaN,NaN,datos/imagenes\Rigel\7Rigel0009 Bx3 Halfa35nm ...,7,...,Rigel,17-03-15,15,21:19:47,0.144100,0.008017,0.004628,0.144100,0.008017,0.004628
8,Betelgeuse,Halfa-35 nm,F,51.0,147.0,NaN,NaN,NaN,datos/imagenes\Beltegeuse\8Betelgeuse0012 Bx3 ...,8,...,Betelgeuse,17-03-15,15,21:41:53,0.641222,0.008581,0.004954,0.641222,0.008581,0.004954
9,Betelgeuse,Halfa-35 nm,B/L+C,30.0,NaN,133.0,238.0,4X,datos/imagenes\Beltegeuse\9Betelgeuse0014 Bx3 ...,9,...,Betelgeuse,17-03-15,15,21:51:31,0.483885,0.015082,0.008708,0.483885,0.015082,0.008708
10,Betelgeuse,Halfa-35 nm,B,30.0,238.0,NaN,NaN,NaN,datos/imagenes\Beltegeuse\10Betelgeuse0016 Bx3...,10,...,Betelgeuse,17-03-15,15,22:01:11,0.322587,0.003800,0.002194,0.322587,0.003800,0.002194
11,Betelgeuse,Halfa-35 nm,B,30.0,133.0,NaN,NaN,NaN,datos/imagenes\Beltegeuse\11Betelgeuse0017 Bx3...,11,...,Betelgeuse,17-03-15,15,22:05:53,0.211979,0.018689,0.010790,0.211979,0.018689,0.010790
12,Sirio,Halfa-35 nm,B,30.0,133.0,NaN,NaN,NaN,datos/imagenes\Sirio\12Sirio0006 Bx3 Halfa35nm...,12,...,Sirius,17-03-16,16,21:47:29,0.342583,0.000277,0.000160,0.342583,0.000277,0.000160
13,Rigel,Halfa-7 nm,F,51.0,147.0,NaN,NaN,NaN,datos/imagenes\Rigel\13Rigel0004 Bx3 Halfa35nm...,13,...,Rigel,17-03-23,23,20:46:30,0.308249,0.003382,0.001953,0.308249,0.003382,0.001953
14,Sirio,Halfa-35 nm,B,30.0,238.0,NaN,NaN,NaN,datos/imagenes\Sirio\14Sirio0009 Bx3 Halfa35nm...,14,...,Sirius,17-03-23,23,21:15:50,0.015108,0.001886,0.001089,0.015108,0.001886,0.001089
15,Sirio,Halfa-35 nm,B,30.0,133.0,NaN,NaN,NaN,datos/imagenes\Sirio\15Sirio0010 Bx3 Halfa35nm...,15,...,Sirius,17-03-23,23,21:20:55,0.268869,0.013899,0.008025,0.268869,0.013899,0.008025
16,Sirio,Halfa-35 nm,E,50.0,222.0,NaN,NaN,NaN,datos/imagenes\Sirio\16Sirio0012 Bx3 Halfa35nm...,16,...,Sirius,17-03-23,23,21:29:27,0.139991,0.021037,0.012146,0.139991,0.021037,0.012146
17,Sirio,Halfa-35 nm,C,65.0,162.0,NaN,NaN,NaN,datos/imagenes\Sirio\17Sirio0014 Bx3 Halfa35nm...,17,...,Sirius,17-03-23,23,21:35:19,0.205609,0.051177,0.029547,0.205609,0.051177,0.029547
18,Sirio,Hbeta-8.5nm,B,30.0,133.0,NaN,NaN,NaN,datos/imagenes\Sirio\18Sirio0016 Bx3 Hbeta 8.5...,18,...,Sirius,17-03-23,23,21:44:25,0.060419,0.002892,0.001669,0.060419,0.002892,0.001669
19,Sirio,Halfa-35 nm,C,66.0,162.0,NaN,NaN,NaN,datos/imagenes\Sirio\19Sirio0001 Bx3 Halfa35nm...,19,...,Sirius,17-03-29,29,21:32:34,0.372131,0.017874,0.010320,0.372131,0.017874,0.010320
20,Sirio,Hbeta-8.5nm,B,66.0,162.0,NaN,NaN,NaN,datos/imagenes\Sirio\20Sirio0002 Bx3 Hbeta8.5n...,20,...,Sirius,17-03-29,29,21:36:56,0.072809,0.004383,0.002530,0.072809,0.004383,0.002530
21,Sirio,Halfa-35 nm,D,66.0,205.0,NaN,NaN,NaN,datos/imagenes\Sirio\21Sirio0004 Bx3 Halfa35n...,21,...,Sirius,17-03-29,29,21:45:14,0.138379,0.003587,0.002071,0.138379,0.003587,0.002071
22,Sirio,Halfa-35 nm,A,90.0,187.0,NaN,NaN,NaN,datos/imagenes\Sirio\22Sirio0006 Bx3 Halfa35n...,22,...,Sirius,17-03-29,29,21:48:54,0.226591,0.002237,0.001291,0.226591,0.002237,0.001291
23,Sirio,Hbeta-8.5nm,A,90.0,187.0,NaN,NaN,NaN,datos/imagenes\Sirio\23Sirio0007 Bx3 Hbeta8.5n...,23,...,Sirius,17-03-29,29,21:51:23,0.139635,0.002157,0.001246,0.139635,0.002157,0.001246
24,GammaLeo,Halfa-35 nm,F,51.0,147.0,NaN,NaN,NaN,datos/imagenes\Gamma Leo\24Gamma Leo0003 Bx3 H...,24,...,GammaLeo,17-04-07,7,23:00:37,NaN,NaN,NaN,NaN,NaN,NaN
25,GammaLeo,sF,-,NaN,NaN,NaN,NaN,Estrella,datos/imagenes\Gamma Leo\25Gamma Leo0001 Bx3 s...,25,...,GammaLeo,17-04-07,7,22:45:11,NaN,NaN,NaN,NaN,NaN,NaN

Por último calculamos el error (ojo si cambiamos las medidas habria que modificar esto, la t_student esta harcoded)

![table](datos/t_student.jpeg)

In [110]:
df3['E_acc']=df3["S_tip"]*9.925 #* 4.3027 #

Vemos lo que hay

In [111]:
df3.keys()

Index(['Objeto', 'Filtro', 'Disco', 'D (mm)', 'L (mm)', 'L1 (mm)', 'L2 (mm)',
       'Notas', 'PATH', 'Imagen', '$\lambda$', '$d\lambda$', 'alphap',
       'alphap_mas', 'filtername', 'starname', 'DATE', 'DAY', 'HOUR',
       'V_media_antigua', 'S_antigua', 'S_tip_antigua', 'V_media', 'S',
       'S_tip', 'E_acc'],
      dtype='object')

In [112]:
df3.head()

,Objeto,Filtro,Disco,D (mm),L (mm),L1 (mm),L2 (mm),Notas,PATH,Imagen,...,DATE,DAY,HOUR,V_media_antigua,S_antigua,S_tip_antigua,V_media,S,S_tip,E_acc
Imagen,,,,,,,,,,,,,,,,,,,,,
1,Sirio,Halfa-7 nm,I,22.0,220.0,NaN,NaN,NaN,datos/imagenes\Sirio\1Sirio0005 Bx3 Halfa 7 nm...,1,...,17-03-10,10,20:48:51,0.094463,0.017632,0.010180,0.094463,0.017632,0.010180,0.101035
2,Sirio,Halfa-7 nm,H,22.0,158.0,NaN,NaN,NaN,datos/imagenes\Sirio\2Sirio0007 Bx3 Halfa 7 nm...,2,...,17-03-10,10,20:54:18,0.033639,0.014732,0.008506,0.033639,0.014732,0.008506,0.084420
3,Sirio,Halfa-7 nm,G,61.0,178.0,NaN,NaN,NaN,datos/imagenes\Sirio\3Sirio0011 Bx3 Halfa 7 nm...,3,...,17-03-10,10,21:05:53,0.277885,0.002123,0.001226,0.277885,0.002123,0.001226,0.012167
4,Rigel,Halfa-7 nm,E,51.0,222.0,NaN,NaN,NaN,datos/imagenes\Rigel\4Rigel0002 Bx3 Halfa7nm I...,4,...,17-03-15,15,20:38:22,0.096563,0.003182,0.001837,0.096563,0.003182,0.001837,0.018232
5,Rigel,Halfa-7 nm,NaN,NaN,NaN,NaN,NaN,Doble,datos/imagenes\Rigel\5Rigel0003 sB Halfa7nm Im...,5,...,17-03-15,15,20:43:57,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [113]:
df3[['Imagen','Objeto','DATE','DAY','HOUR','V_media','E_acc']].head(6)

        Imagen Objeto      DATE  DAY      HOUR   V_media     E_acc
Imagen
1            1  Sirio  17-03-10   10  20:48:51  0.094463  0.101035
2            2  Sirio  17-03-10   10  20:54:18  0.033639  0.084420
3            3  Sirio  17-03-10   10  21:05:53  0.277885  0.012167
4            4  Rigel  17-03-15   15  20:38:22  0.096563  0.018232
5            5  Rigel  17-03-15   15  20:43:57       NaN       NaN
6            6  Rigel  17-03-15   15  21:14:55  0.439454  0.045045

In [114]:
df3.dtypes

Objeto              object
Filtro              object
Disco               object
D (mm)             float64
L (mm)             float64
L1 (mm)            float64
L2 (mm)            float64
Notas               object
PATH                object
Imagen               int64
$\lambda$          float64
$d\lambda$         float64
alphap             float64
alphap_mas         float64
filtername          object
starname            object
DATE                object
DAY                  int64
HOUR                object
V_media_antigua    float64
S_antigua          float64
S_tip_antigua      float64
V_media            float64
S                  float64
S_tip              float64
E_acc              float64
dtype: object

In [115]:
df3

,Objeto,Filtro,Disco,D (mm),L (mm),L1 (mm),L2 (mm),Notas,PATH,Imagen,...,DATE,DAY,HOUR,V_media_antigua,S_antigua,S_tip_antigua,V_media,S,S_tip,E_acc
Imagen,,,,,,,,,,,,,,,,,,,,,
1,Sirio,Halfa-7 nm,I,22.0,220.0,NaN,NaN,NaN,datos/imagenes\Sirio\1Sirio0005 Bx3 Halfa 7 nm...,1,...,17-03-10,10,20:48:51,0.094463,0.017632,0.010180,0.094463,0.017632,0.010180,0.101035
2,Sirio,Halfa-7 nm,H,22.0,158.0,NaN,NaN,NaN,datos/imagenes\Sirio\2Sirio0007 Bx3 Halfa 7 nm...,2,...,17-03-10,10,20:54:18,0.033639,0.014732,0.008506,0.033639,0.014732,0.008506,0.084420
3,Sirio,Halfa-7 nm,G,61.0,178.0,NaN,NaN,NaN,datos/imagenes\Sirio\3Sirio0011 Bx3 Halfa 7 nm...,3,...,17-03-10,10,21:05:53,0.277885,0.002123,0.001226,0.277885,0.002123,0.001226,0.012167
4,Rigel,Halfa-7 nm,E,51.0,222.0,NaN,NaN,NaN,datos/imagenes\Rigel\4Rigel0002 Bx3 Halfa7nm I...,4,...,17-03-15,15,20:38:22,0.096563,0.003182,0.001837,0.096563,0.003182,0.001837,0.018232
5,Rigel,Halfa-7 nm,NaN,NaN,NaN,NaN,NaN,Doble,datos/imagenes\Rigel\5Rigel0003 sB Halfa7nm Im...,5,...,17-03-15,15,20:43:57,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Rigel,Halfa-35 nm,F,51.0,147.0,NaN,NaN,NaN,datos/imagenes\Rigel\6Rigel0008 Bx3 Halfa35nm ...,6,...,17-03-15,15,21:14:55,0.439454,0.007861,0.004539,0.439454,0.007861,0.004539,0.045045
7,Rigel,Halfa-35 nm,E,51.0,222.0,NaN,NaN,NaN,datos/imagenes\Rigel\7Rigel0009 Bx3 Halfa35nm ...,7,...,17-03-15,15,21:19:47,0.144100,0.008017,0.004628,0.144100,0.008017,0.004628,0.045938
8,Betelgeuse,Halfa-35 nm,F,51.0,147.0,NaN,NaN,NaN,datos/imagenes\Beltegeuse\8Betelgeuse0012 Bx3 ...,8,...,17-03-15,15,21:41:53,0.641222,0.008581,0.004954,0.641222,0.008581,0.004954,0.049168
9,Betelgeuse,Halfa-35 nm,B/L+C,30.0,NaN,133.0,238.0,4X,datos/imagenes\Beltegeuse\9Betelgeuse0014 Bx3 ...,9,...,17-03-15,15,21:51:31,0.483885,0.015082,0.008708,0.483885,0.015082,0.008708,0.086422
10,Betelgeuse,Halfa-35 nm,B,30.0,238.0,NaN,NaN,NaN,datos/imagenes\Beltegeuse\10Betelgeuse0016 Bx3...,10,...,17-03-15,15,22:01:11,0.322587,0.003800,0.002194,0.322587,0.003800,0.002194,0.021777
11,Betelgeuse,Halfa-35 nm,B,30.0,133.0,NaN,NaN,NaN,datos/imagenes\Beltegeuse\11Betelgeuse0017 Bx3...,11,...,17-03-15,15,22:05:53,0.211979,0.018689,0.010790,0.211979,0.018689,0.010790,0.107091
12,Sirio,Halfa-35 nm,B,30.0,133.0,NaN,NaN,NaN,datos/imagenes\Sirio\12Sirio0006 Bx3 Halfa35nm...,12,...,17-03-16,16,21:47:29,0.342583,0.000277,0.000160,0.342583,0.000277,0.000160,0.001589
13,Rigel,Halfa-7 nm,F,51.0,147.0,NaN,NaN,NaN,datos/imagenes\Rigel\13Rigel0004 Bx3 Halfa35nm...,13,...,17-03-23,23,20:46:30,0.308249,0.003382,0.001953,0.308249,0.003382,0.001953,0.019379
14,Sirio,Halfa-35 nm,B,30.0,238.0,NaN,NaN,NaN,datos/imagenes\Sirio\14Sirio0009 Bx3 Halfa35nm...,14,...,17-03-23,23,21:15:50,0.015108,0.001886,0.001089,0.015108,0.001886,0.001089,0.010804
15,Sirio,Halfa-35 nm,B,30.0,133.0,NaN,NaN,NaN,datos/imagenes\Sirio\15Sirio0010 Bx3 Halfa35nm...,15,...,17-03-23,23,21:20:55,0.268869,0.013899,0.008025,0.268869,0.013899,0.008025,0.079645
16,Sirio,Halfa-35 nm,E,50.0,222.0,NaN,NaN,NaN,datos/imagenes\Sirio\16Sirio0012 Bx3 Halfa35nm...,16,...,17-03-23,23,21:29:27,0.139991,0.021037,0.012146,0.139991,0.021037,0.012146,0.120546
17,Sirio,Halfa-35 nm,C,65.0,162.0,NaN,NaN,NaN,datos/imagenes\Sirio\17Sirio0014 Bx3 Halfa35nm...,17,...,17-03-23,23,21:35:19,0.205609,0.051177,0.029547,0.205609,0.051177,0.029547,0.293257
18,Sirio,Hbeta-8.5nm,B,30.0,133.0,NaN,NaN,NaN,datos/imagenes\Sirio\18Sirio0016 Bx3 Hbeta 8.5...,18,...,17-03-23,23,21:44:25,0.060419,0.002892,0.001669,0.060419,0.002892,0.001669,0.016569
19,Sirio,Halfa-35 nm,C,66.0,162.0,NaN,NaN,NaN,datos/imagenes\Sirio\19Sirio0001 Bx3 Halfa35nm...,19,...,17-03-29,29,21:32:34,0.372131,0.017874,0.010320,0.372131,0.017874,0.010320,0.102422
20,Sirio,Hbeta-8.5nm,B,66.0,162.0,NaN,NaN,NaN,datos/imagenes\Sirio\20Sirio0002 Bx3 Hbeta8.5n...,20,...,17-03-29,29,21:36:56,0.072809,0.004383,0.002530,0.072809,0.004383,0.002530,0.025113
21,Sirio,Halfa-35 nm,D,66.0,205.0,NaN,NaN,NaN,datos/imagenes\Sirio\21Sirio0004 Bx3 Halfa35n...,21,...,17-03-29,29,21:45:14,0.138379,0.003587,0.002071,0.138379,0.003587,0.002071,0.020552
22,Sirio,Halfa-35 nm,A,90.0,187.0,NaN,NaN,NaN,datos/imagenes\Sirio\22Sirio0006 Bx3 Halfa35n...,22,...,17-03-29,29,21:48:54,0.226591,0.002237,0.001291,0.226591,0.002237,0.001291,0.012818
23,Sirio,Hbeta-8.5nm,A,90.0,187.0,NaN,NaN,NaN,datos/imagenes\Sirio\23Sirio0007 Bx3 Hbeta8.5n...,23,...,17-03-29,29,21:51:23,0.139635,0.002157,0.001246,0.139635,0.002157,0.001246,0.012362
24,GammaLeo,Halfa-35 nm,F,51.0,147.0,NaN,NaN,NaN,datos/imagenes\Gamma Leo\24Gamma Leo0003 Bx3 H...,24,...,17-04-07,7,23:00:37,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,GammaLeo,sF,-,NaN,NaN,NaN,NaN,Estrella,datos/imagenes\Gamma Leo\25Gamma Leo0001 Bx3 s...,25,...,17-04-07,7,22:45:11,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [116]:
df3.to_hdf('intermedio/tabla.h5',key='df', mode='w')

C:\Users\ivian\AppData\Local\Temp\ipykernel_22484\850098308.py:1: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block2_values] [items->Index(['Objeto', 'Filtro', 'Disco', 'Notas', 'PATH', 'filtername', 'starname',
       'DATE', 'HOUR'],
      dtype='object')]

  df3.to_hdf('intermedio/tabla.h5',key='df', mode='w')

In [117]:
if not os.path.isdir("productos/"):
    os.makedirs("productos/")
df3.to_excel("productos/tabla_excel.xlsx",engine="openpyxl")